### ISSUE TITLE
Currency list needs to be updated to include XBB

### ISSUE THREAD

**Issue by reyley** [dahlia/iso4217#13]
Current version does not include the XBB currency but it's in the most recent XML file

```python
>>> import iso4217
>>> iso4217.__version__
'1.8.20211001'
>>> iso4217.Currency.xbb
Traceback (most recent call last):
  File "/Users/rachel.ilan/.pyenv/versions/3.8.12/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Users/rachel.ilan/.pyenv/versions/3.8.12/lib/python3.8/enum.py", line 384, in __getattr__
    raise AttributeError(name) from None
AttributeError: xbb
```

Updated currency list here: https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list_one.xml
Includes:
```xml
<CcyNtry>
<CtryNm>ZZ02_Bond Markets Unit European_EMU-6</CtryNm>
<CcyNm>Bond Markets Unit European Monetary Unit (E.M.U.-6)</CcyNm>
<Ccy>XBB</Ccy>
<CcyNbr>956</CcyNbr>
<CcyMnrUnts>N.A.</CcyMnrUnts>
</CcyNtry>
```

**Comment by dahlia** [comment]
Released a new version: [iso4217 1.9.20220401](https://pypi.org/project/iso4217/1.9.20220401/).

```pycon
>>> import iso4217
>>> iso4217.__version__
'1.9.20220401'
>>> iso4217.Currency.xbb
<Currency.xbb: 'XBB'>
```
